"""
Root Query type, used for get information about the system.
"""
type Query {
    """
    PROTECTED
    Used to know with which account you're logged in. Returns a User type (click User for see more).
    """
    me: User!
    """
    Simple query for check if the system works. Returns a string.
    """
    hello: String!
    """
    PROTECTED
    Used to get all users of the system. Returns a list of Users type (click User for see more).
    """
    users: [User!]!
    """
    PROTECTED
    Used to get a user by id. Returns a User type (click User for see more).
    """
    getUserById(id: ID!): User!
    """
    PROTECTED
    Used to get pastes in the system. Returns a list of Pastes type (click Paste for see more).
    """
    pastes: [Paste!]!
    """
    PROTECTED
    Used to get a paste by id. Returns a Paste type (click Paste for see more).
    """
    getPasteById(id: ID!): Paste!
    """
    PROTECTED
    Used to get pastes by author id. Returns a list of Pastes type (click Paste for see more).
    """
    getPastesByAuthor(authorId: ID!): [Paste!]!
}
