name: Integration Tests

on:
    pull_request:
        branches: ['dev']
        paths:
            - 'tests/integration/**'
    push:
        branches: ['dev']
        paths:
            - 'tests/integration/**'
jobs:
    build:
        runs-on: self-test # windows 64b

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: yarn install
            - run: yarn test:integration
